//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuseinessEntityLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DREntities : DbContext
    {
        public DREntities()
            : base("name=DREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblUserGroup> tblUserGroups { get; set; }
        public virtual DbSet<tblUserAccessRole> tblUserAccessRoles { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
    
        public virtual ObjectResult<spSearch_Result> spSearch(Nullable<int> receiptNumber, string customerName, string companyName, string deviceModel)
        {
            var receiptNumberParameter = receiptNumber.HasValue ?
                new ObjectParameter("ReceiptNumber", receiptNumber) :
                new ObjectParameter("ReceiptNumber", typeof(int));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var deviceModelParameter = deviceModel != null ?
                new ObjectParameter("DeviceModel", deviceModel) :
                new ObjectParameter("DeviceModel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSearch_Result>("spSearch", receiptNumberParameter, customerNameParameter, companyNameParameter, deviceModelParameter);
        }
    }
}
