//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuseinessEntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Post { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UserGroupID { get; set; }
        public bool Status { get; set; }
    
        public virtual tblUserGroup tblUserGroup { get; set; }
    }
}
