//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuseinessEntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserAccessRole
    {
        public int ID { get; set; }
        public string Section { get; set; }
        public Nullable<bool> IsSave { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsSearch { get; set; }
        public int UserGroupID { get; set; }
    
        public virtual tblUserGroup tblUserGroup { get; set; }
    }
}
